"""init

Revision ID: 146cc3df2a1c
Revises: 
Create Date: 2018-03-31 08:48:21.720124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '146cc3df2a1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('order', 'date')
    op.add_column('room', sa.Column('available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'available')
    op.add_column('order', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('order', 'year')
    op.drop_column('order', 'month')
    op.drop_column('order', 'day')
    op.drop_column('order', 'create_time')
    # ### end Alembic commands ###
