"""second

Revision ID: 2a6cbcccd8a8
Revises: 146cc3df2a1c
Create Date: 2018-03-31 11:23:16.264694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6cbcccd8a8'
down_revision = '146cc3df2a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('open_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'open_id')
    # ### end Alembic commands ###
